### ISSUE TITLE
hello dear 

### ISSUE THREAD

**Issue by moh241eng** [android-cjj/JJSearchViewAnim#4]
Dear 
i have Issues please 

thank you 
![untitled](https://cloud.githubusercontent.com/assets/7375759/23902721/c43f63aa-08ca-11e7-921e-5c4edd0c5ad5.jpg)

**Comment by Axrorxoja** [comment]
manually change build.gradle to latest version build tools at time it's 25.3

**Comment by moh241eng** [comment]
Thank you dear Daaark 

done
